import type { NavigatorScreenParams } from '@react-navigation/native';
import type { MainTabParamList } from '../navigation/MainTabNavigator';

export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  SignUp: undefined;
  ForgotPassword: { screen_heading: string };
  OTPVerification: {
    email: string;
    type: 'forgot_password' | 'email_verification' | 'update_email';
    user?: any;
    token?: string;
    fromLogin?: boolean;
  };
  ChangePassword: { email: string; resetToken: string };
  // Optional params: lets callers open a specific tab, e.g. { screen: 'Home' }.
  Main: NavigatorScreenParams<MainTabParamList> | undefined;
  TwofactorOTP: { token: string; user: any };
  // token is optional: ReferralScreen treats a missing token as "not signed in".
  ReferralScreen: { token?: string; user: any; fromLogin?: boolean; isNewUser?: boolean };
  MyProfileScreen: undefined;
  UpdateEmail: undefined;
  TwoFactorScreen: undefined;
  NotificationPrefs: undefined;
  HelpCenter: undefined;
  ContactSupport: undefined;
  Page: undefined;
  AllActivity: undefined;
  InternalReferral: undefined;
  Wallet: undefined;
  DepositScreen: undefined;
  WithdrawScreen: {
    method: 'Lightining' | 'BTC';
  };
  FAQScreen: undefined;
  SupportScreen: undefined;
  Store: undefined;
  MakePaymentScreen: { plan: any };
  CustomQuote: undefined;
  DeleteAccount: undefined;
  NotificationScreen: undefined;
  Sidebar: undefined;
  AchievementsScreen: undefined;
  WatchVideoScreen: undefined;
  NotificationPreferencesScreen: undefined;
  ChangePasswordScreen: { email: string; resetToken: string };
  DailyRewardsScreen: undefined;
  CryptoDepositScreen: { amount: any; currency: string; notes: string };
  BalanceHistoryScreen: undefined;
  TwoFactorLoginScreen: {token: string;user: any; fromLogin?: boolean; };
  MyMiner: undefined;
  WebViewScreen: { url: string; title: string };
  AboutUsScreen: undefined;
  MyProfileEditScreen: undefined;
  TradingScreen: undefined;
  SpinAndWin: undefined;
  MemoryCardMatch: undefined;
  ScratchAndWin: undefined;
  TapToBomb: undefined;
  HigherLower: undefined;
  RockPaperScissors: undefined;
  LuckyDice: undefined;
  TreasureChest: undefined;
  ReactionTap: undefined;
  OddOneOut: undefined;
  NumberRush: undefined;
  SimonSays: undefined;
  GuessBtcPrice: undefined;
  SlotMachine: undefined;
  WordScramble: undefined;
  MathBlitz: undefined;
  SpeedTap: undefined;
  WhackABlock: undefined;
  StackTower: undefined;
  CrashCashOut: undefined;
  CryptoQuiz: undefined;
  ColorClash: undefined;
  SwipeSort: undefined;
  ApptroveDebug: undefined;
  SuperPrivileges: undefined;
};
